blacklist: []
build_space: odroid-build
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Debug
devel_layout: linked
devel_space: odroid-devel
extend_path: null
install: false
install_space: odroid-install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
